#/bin/bash

# almost sure
export WITH_AFB_CALL_SYNC=OFF
export WITH_AFB_DEBUG=OFF
export WITH_AFB_TRACE=OFF
export WITH_API_CREATOR=OFF
export WITH_CALL_PERSONALITY=OFF
export WITH_CASE_FOLDING=OFF
export WITH_CLOCK_GETTIME=OFF
export WITH_DIRENT=OFF
export WITH_DYNAMIC_BINDING=OFF
export WITH_ENVIRONMENT=OFF
export WITH_EPOLL=OFF
export WITH_EVENTFD=OFF
export WITH_EXTENSION=OFF
export WITH_FDEV_EPOLL=OFF
export WITH_FDEV_POLL=ON
export WITH_FDEV_SELECT=OFF
export WITH_FDEV_SYSTEMD=OFF
export WITH_FNMATCH=OFF
export WITH_GNUTLS=OFF
export WITH_L4VSOCK=OFF
export WITH_LIBMAGIC=OFF
export WITH_LIBMICROHTTPD=OFF
export WITH_LIBUUID=OFF
export WITH_LOCALE_FOLDER=OFF
export WITH_LOCALE_SEARCH_NODE=OFF
export WITH_OPENAT=OFF
export WITHOUT_CYNAGORA=ON
export WITHOUT_JSON_C=ON
export WITHOUT_TESTS=ON
export WITH_RANDOM_R=OFF
export WITH_REALPATH=OFF
export WITH_RPC_V1=OFF
export WITH_RPC_V3=ON
export WITH_RPUTILS_STATIC=ON
export WITH_SIG_MONITOR_DUMPSTACK=OFF
export WITH_SIG_MONITOR_FOR_CALL=OFF
export WITH_SIG_MONITOR_SIGNALS=OFF
export WITH_SIG_MONITOR_TIMERS=OFF
export WITH_SUPERVISION=OFF
export WITH_SYSTEMD=OFF
export WITH_SYS_UIO=OFF
export WITH_TRACK_JOB_CALL=OFF
export WITH_UNIX_SOCKET=OFF
export WITH_WSCLIENT_URI_COPY=OFF

# tunable
export ARCH32=OFF
export WITH_AFB_HOOK=OFF
export WITH_CRED=OFF
export WITH_REPLY_JOB=ON
export WITH_REQ_PROCESS_ASYNC=ON

# unsure
export WITH_THREAD_LOCAL=ON

# buildir
export bd=build-zephyr

$(dirname $0)/mkbuild.sh "$@"

